### ISSUE TITLE
Teleshadow ran but no data gathering

### ISSUE THREAD

**Issue by totoroha** [ParsingTeam/TeleShadow2#1]
Dear Team,

I tried to build the executable with SMTP info cause i don't have the token information. However, when i executed the program in the folder where i have telegram desktop program, i waited for about 30m while continued my conversation with my colleague to test the program. In the end, i did not see any hihacked session at all.

Would you please guide me through the process of testing this product?

Sincerely,

Peter

P/S: i joined the telegram channel of your team but could not find the video clip that i want.

**Comment by ParsingTeam** [comment]
Hello, That should work, try with telegram api method. and if you using smtp service, Don't forget to enable less secure app. at gmail https://myaccount.google.com/lesssecureapps?pli=1
